"""
outputs.py — Rich Output Generation for UTE
=============================================
Generate downloadable files from UTE answers:
  - PDF   (reportlab)
  - DOCX  (python-docx)
  - MD    (plain text — always available)
  - PNG   (SVG diagram rendered to image via cairosvg, fallback: SVG)

Called after Claude answers — the output_type is inferred from the query
or explicitly requested by the user ("give me a PDF", "create a Word doc").
"""

import io
import os
import re
import datetime
from typing import Optional


# ── Output type detection ─────────────────────────────────────

def detect_output_type(query: str, answer: str) -> str:
    """
    Determine what file format the output should be.
    Returns: 'pdf' | 'docx' | 'md' | 'none'
    """
    ql = query.lower()

    if re.search(r'\b(?:pdf|as pdf|in pdf|save as pdf|download pdf)\b', ql):
        return 'pdf'
    if re.search(r'\b(?:word|docx|doc|word document|ms word)\b', ql):
        return 'docx'
    if re.search(r'\b(?:markdown|\.md|md file)\b', ql):
        return 'md'

    # Long structured answers → PDF
    header_count = len(re.findall(r'(?:^|\n)#{1,3} ', answer))
    if header_count >= 3 or len(answer) > 2000:
        return 'pdf'
    if header_count >= 2:
        return 'md'

    # Task queries that produce documents
    if re.search(r'\b(?:report|proposal|strategy|plan|brief|analysis|'
                 r'presentation|document|summary|overview)\b', ql):
        return 'pdf'

    return 'none'


# ── PDF generation ────────────────────────────────────────────

def generate_pdf(title: str, answer: str,
                 query: str = '', author: str = 'UTE') -> Optional[bytes]:
    """Generate a PDF from the answer text. Returns bytes or None."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        HRFlowable, PageBreak)
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            leftMargin=2.5*cm, rightMargin=2.5*cm,
            topMargin=2.5*cm, bottomMargin=2.5*cm,
            title=title, author=author,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'UTETitle', parent=styles['Title'],
            fontSize=20, textColor=colors.HexColor('#f59e0b'),
            spaceAfter=6,
        )
        subtitle_style = ParagraphStyle(
            'UTESubtitle', parent=styles['Normal'],
            fontSize=9, textColor=colors.HexColor('#a0a0ac'),
            spaceAfter=20,
        )
        h1_style = ParagraphStyle(
            'UTEH1', parent=styles['Heading1'],
            fontSize=14, textColor=colors.HexColor('#e8e8ec'),
            spaceBefore=14, spaceAfter=6,
            borderPad=0,
        )
        h2_style = ParagraphStyle(
            'UTEH2', parent=styles['Heading2'],
            fontSize=12, textColor=colors.HexColor('#a0a0ac'),
            spaceBefore=10, spaceAfter=4,
        )
        body_style = ParagraphStyle(
            'UTEBody', parent=styles['Normal'],
            fontSize=10, leading=16,
            textColor=colors.HexColor('#2a2a2e'),
            spaceAfter=8,
        )
        bullet_style = ParagraphStyle(
            'UTEBullet', parent=body_style,
            leftIndent=20, firstLineIndent=-12,
            spaceAfter=4,
        )

        story = []

        # Title block
        story.append(Paragraph(_escape_xml(title), title_style))
        now = datetime.datetime.now().strftime('%B %d, %Y')
        story.append(Paragraph(
            f'Generated by UTE · Unified Theory Engine · {now}',
            subtitle_style
        ))
        story.append(HRFlowable(
            width='100%', thickness=1,
            color=colors.HexColor('#f59e0b'), spaceAfter=16
        ))

        # Parse and render the answer
        for block in _parse_md_blocks(answer):
            btype = block['type']
            text  = block['text']

            if btype == 'h1':
                story.append(Paragraph(_escape_xml(text), h1_style))
            elif btype == 'h2':
                story.append(Paragraph(_escape_xml(text), h2_style))
            elif btype == 'h3':
                story.append(Paragraph(
                    f'<b>{_escape_xml(text)}</b>', body_style))
            elif btype == 'bullet':
                story.append(Paragraph(
                    f'• {_escape_xml(text)}', bullet_style))
            elif btype == 'numbered':
                story.append(Paragraph(
                    _escape_xml(text), bullet_style))
            elif btype == 'hr':
                story.append(HRFlowable(
                    width='100%', thickness=0.5,
                    color=colors.HexColor('#cccccc'), spaceAfter=8))
            else:
                # Body text — handle inline bold/italic
                rich = _md_inline_to_xml(text)
                story.append(Paragraph(rich, body_style))

            if btype in ('h1', 'h2'):
                story.append(Spacer(1, 4))

        # Footer note
        story.append(Spacer(1, 20))
        story.append(HRFlowable(
            width='100%', thickness=0.5,
            color=colors.HexColor('#cccccc'), spaceAfter=6))
        story.append(Paragraph(
            'Generated by UTE — Unified Theory Engine · ute-production.up.railway.app',
            ParagraphStyle('footer', parent=styles['Normal'],
                           fontSize=7, textColor=colors.HexColor('#a0a0ac'),
                           alignment=TA_CENTER)
        ))

        doc.build(story)
        return buf.getvalue()

    except Exception as e:
        print(f"  [PDF] {e}")
        return None


# ── DOCX generation ───────────────────────────────────────────

def generate_docx(title: str, answer: str,
                  query: str = '', author: str = 'UTE') -> Optional[bytes]:
    """Generate a Word document from the answer. Returns bytes or None."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Page margins
        for section in doc.sections:
            section.top_margin    = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin   = Inches(1.2)
            section.right_margin  = Inches(1.2)

        # Title
        t = doc.add_heading(title, 0)
        t.runs[0].font.color.rgb = RGBColor(0xf5, 0x9e, 0x0b)
        t.runs[0].font.size = Pt(20)

        # Subtitle
        sub = doc.add_paragraph(
            f'Generated by UTE · {datetime.datetime.now().strftime("%B %d, %Y")}'
        )
        sub.runs[0].font.size = Pt(9)
        sub.runs[0].font.color.rgb = RGBColor(0xa0, 0xa0, 0xac)

        doc.add_paragraph()

        # Parse and render
        for block in _parse_md_blocks(answer):
            btype = block['type']
            text  = block['text']

            if btype == 'h1':
                doc.add_heading(text, 1)
            elif btype == 'h2':
                doc.add_heading(text, 2)
            elif btype == 'h3':
                p = doc.add_heading(text, 3)
            elif btype in ('bullet', 'numbered'):
                p = doc.add_paragraph(text, style='List Bullet')
                p.runs[0].font.size = Pt(10) if p.runs else None
            else:
                p = doc.add_paragraph()
                _add_inline_runs(p, text)

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph(
            'Generated by UTE — Unified Theory Engine · ute-production.up.railway.app'
        )
        footer.runs[0].font.size = Pt(7)
        footer.runs[0].font.color.rgb = RGBColor(0xa0, 0xa0, 0xac)

        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()

    except Exception as e:
        print(f"  [DOCX] {e}")
        return None


# ── Markdown generation ───────────────────────────────────────

def generate_md(title: str, answer: str,
                query: str = '') -> bytes:
    """Generate a Markdown file. Always works — no dependencies."""
    now   = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [
        f"# {title}",
        f"",
        f"*Generated by UTE — Unified Theory Engine · {now}*",
        f"",
        f"---",
        f"",
        answer,
        f"",
        f"---",
        f"*[ute-production.up.railway.app](https://ute-production.up.railway.app)*",
    ]
    return '\n'.join(lines).encode('utf-8')


# ── Main entry point ──────────────────────────────────────────

def generate_output(
    query:       str,
    answer:      str,
    output_type: str = 'auto',
    user_name:   str = 'UTE',
) -> Optional[dict]:
    """
    Generate a downloadable file from a UTE answer.

    output_type: 'auto' | 'pdf' | 'docx' | 'md' | 'none'
    Returns: {'content': bytes, 'mime': str, 'name': str, 'type': str}
    or None if no file should be generated.
    """
    if output_type == 'auto':
        output_type = detect_output_type(query, answer)
    if output_type == 'none':
        return None

    # Build title from query
    words = re.findall(r'\b\w{3,}\b', query.lower())[:6]
    title = ' '.join(w.capitalize() for w in words) or 'UTE Output'
    fname_base = '_'.join(words[:5]) if words else 'ute_output'

    if output_type == 'pdf':
        content = generate_pdf(title, answer, query, user_name)
        if content:
            return {'content': content, 'mime': 'application/pdf',
                    'name': f'{fname_base}.pdf', 'type': 'pdf'}
        # Fallback to MD if PDF fails
        output_type = 'md'

    if output_type == 'docx':
        content = generate_docx(title, answer, query, user_name)
        if content:
            return {
                'content': content,
                'mime': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'name': f'{fname_base}.docx', 'type': 'docx',
            }
        output_type = 'md'

    if output_type == 'md':
        content = generate_md(title, answer, query)
        return {'content': content, 'mime': 'text/markdown',
                'name': f'{fname_base}.md', 'type': 'md'}

    return None


# ── Markdown parser ───────────────────────────────────────────

def _parse_md_blocks(text: str) -> list:
    """Parse markdown text into a list of {type, text} blocks."""
    blocks = []
    for line in text.split('\n'):
        line = line.rstrip()
        if line.startswith('### '):
            blocks.append({'type': 'h3', 'text': line[4:]})
        elif line.startswith('## '):
            blocks.append({'type': 'h2', 'text': line[3:]})
        elif line.startswith('# '):
            blocks.append({'type': 'h1', 'text': line[2:]})
        elif line.startswith('---') or line.startswith('==='):
            blocks.append({'type': 'hr', 'text': ''})
        elif re.match(r'^[-•*]\s+', line):
            blocks.append({'type': 'bullet', 'text': re.sub(r'^[-•*]\s+', '', line)})
        elif re.match(r'^\d+\.\s+', line):
            blocks.append({'type': 'numbered', 'text': re.sub(r'^\d+\.\s+', '', line)})
        elif line:
            blocks.append({'type': 'body', 'text': line})
    return blocks


def _escape_xml(text: str) -> str:
    """Escape text for ReportLab XML."""
    return (text.replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;'))


def _md_inline_to_xml(text: str) -> str:
    """Convert inline markdown to ReportLab XML."""
    text = _escape_xml(text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.+?)\*',     r'<i>\1</i>', text)
    text = re.sub(r'`(.+?)`',       r'<font name="Courier">\1</font>', text)
    return text


def _add_inline_runs(paragraph, text: str):
    """Add text with inline bold/italic to a python-docx paragraph."""
    from docx.shared import Pt
    # Split on **bold** and *italic*
    parts = re.split(r'(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith('*') and part.endswith('*'):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        elif part.startswith('`') and part.endswith('`'):
            run = paragraph.add_run(part[1:-1])
            run.font.name = 'Courier New'
        elif part:
            paragraph.add_run(part)
    for run in paragraph.runs:
        run.font.size = Pt(10)
